# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
    Company.create(company_name: 'Intel')
    Company.create(company_name: 'AMD')
    Company.create(company_name: 'Nvidia')
    Company.create(company_name: 'Radeon')

    Brand.create(brand_name:'Core i7')
    Brand.create(brand_name:'Core 2 Quad')
    Brand.create(brand_name:'Atom')
    Brand.create(brand_name:'Core i5')
    Brand.create(brand_name:'Core i3')
    Brand.create(brand_name:'Pentium')
    Brand.create(brand_name:'Celeron')
    Brand.create(brand_name:'Xeon')
    Brand.create(brand_name:'Athlon')
    Brand.create(brand_name:'Sempron')
    Brand.create(brand_name:'Sempron x64')
    Brand.create(brand_name:'FX')
    Brand.create(brand_name:'Opteron')
    Brand.create(brand_name:'Athlon 64')
    Brand.create(brand_name:'Athlon XP')
    Brand.create(brand_name:'Phenom')
    Brand.create(brand_name:'Turion')
    Brand.create(brand_name:'Core 2 Duo')
    Brand.create(brand_name:'A4')
    Brand.create(brand_name:'A6')
    Brand.create(brand_name:'A8')
    Brand.create(brand_name:'A10')
    Brand.create(brand_name:'Dualcore')
    Brand.create(brand_name:'Core 2 Extreme')

    Brand.create(brand_name:'Geforce')
    Brand.create(brand_name:'Quadro')
    Brand.create(brand_name:'Radeon')
    Brand.create(brand_name:'Firepro')
    Brand.create(brand_name:'FireGL')
    Brand.create(brand_name:'FireMV')

    SocketCpu.create(socket_name:'1150')
    SocketCpu.create(socket_name:'1151')
    SocketCpu.create(socket_name:'2011')
    SocketCpu.create(socket_name:'2011-3')
    SocketCpu.create(socket_name:'Atom')
    SocketCpu.create(socket_name:'1155')
    SocketCpu.create(socket_name:'1156')
    SocketCpu.create(socket_name:'1366')
    SocketCpu.create(socket_name:'478')
    SocketCpu.create(socket_name:'479')
    SocketCpu.create(socket_name:'771')
    SocketCpu.create(socket_name:'775')
    SocketCpu.create(socket_name:'P')

    SocketCpu.create(socket_name:'AM1')
    SocketCpu.create(socket_name:'AM3+')
    SocketCpu.create(socket_name:'FM2')
    SocketCpu.create(socket_name:'754')
    SocketCpu.create(socket_name:'940')
    SocketCpu.create(socket_name:'939')
    SocketCpu.create(socket_name:'A (462)')
    SocketCpu.create(socket_name:'AM2')
    SocketCpu.create(socket_name:'AM2+')
    SocketCpu.create(socket_name:'AM3')
    SocketCpu.create(socket_name:'C32')
    SocketCpu.create(socket_name:'F')
    SocketCpu.create(socket_name:'FM1')
    SocketCpu.create(socket_name:'FM2')
    SocketCpu.create(socket_name:'G34')
    SocketCpu.create(socket_name:'S1')


